### ISSUE TITLE
Ask 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [shubhsk88/realbnb-frontend#6]
Your project looks great.
Excuse my question, I was unable to test your repo.
Do you have an admission page?
Can articles be added from admission?

**Comment by marcebdev** [comment]
Hi @AnonymousWebHacker, thanks for checking out our project!

I'd be happy to help. Im guessing you aren't able to test it due to the backend repo being private. Does that sound about right? We can/should def look into making the backend public as well.

Could you clarify what you mean by an admissions page?

**Comment by AnonymousWebHacker** [comment]
@marcebdev Hi, This is the first time someone on github has seen him as courteous as you are.

The repo is private, it is your decision, however, I would love to see the server (backend) of course.
As above, excuse me, I use a translator, I am Spanish-speaking (Spanish), I was referring to the administration. You already answered me, is that the backend is missing :)
But really, the project is super interesting :1st_place_medal:

**Comment by marcebdev** [comment]
Hey @AnonymousWebHacker thanks for the kind words! Apologies for taking so long to get back as we've both had various life events to attend to but I wanted to let you know you can access the backend here https://github.com/shubhsk88/realbnb-backend 😄

Hope that can help you with your projects!
